### PR TITLE
Integrate Pisces Upstream with CS471-F17-KillMinusNine Changes

### PR DESCRIPTION
**Pull request by sammcmahon**
# KillMinusNine Integration and Syncing
This pull request brings in the changes from the last couple weeks of the KillMinusNine team at BSU, which roughly include bug fixes, changes to CI for TravisCI and AppVeyor, increased use of NuGet for dependency management, and repository cleanup,

## Bug Fixes and Unit Tests
We've been using successful NUnit test outcomes as the primary goal of our work over the last sprint. From a freshly cloned repository with no extra environment setup (e.g. no local postgres instance), on a Windows 10 machine, there are currently 25 failing unit tests out of 283 tests:

screen shot 2018-03-01 at 11 28 21 pm

To run the tests, we installed the NUnit3TestAdapter NuGet package for each application and library in the repository. The Test Explorer window in Visual Studio can then run the tests and show the results.

## Travis CI and AppVeyor Changes
A few changes to Travis CI and AppVeyor were made, most notably running unit tests now during CI and checking them for failure. A new console test runner package was added to the CI scripts to do this.

Currently, we are only running the tests for the Reclamation.Core and Reclamation.TimeSeries libraries as conditions for passing CI. <del>This means that CI will be failing until all the unit tests under these projects pass.</del> *Update: CI is nice and green now.* We plan to change this in the future as the unit tests for the remaining projects get closer to all passing.

## NuGet Dependencies
A number of third-party DLL's stored in the repository were able to be replaced with NuGet packages downloaded when the project is built initially. There are still some left which may potentially be replaced in the future.

## Repository Cleanup
A new gitignore file was also added, and build artifacts, temp files, etc, were able to be removed from the repository.

A new folder for metadata files has been added the the repository source, since these files were all needed by several programs and libraries. We were getting many failing test issues (over 80 or so) due to not being able to find metadata csv files.

### CODE REVIEW

**Comment by ktarbet** [comment]
Appveyor is passing with 3d7144c !

The UI application (Pisces) is giving this error:
image

The error is because these are missing: (Works OK when then are present)
x64\SqLite.Interop.dll
x86\SqLite.Interop.dll

https://system.data.sqlite.org/index.html/doc/trunk/www/downloads.wiki

**Comment by sammcmahon** [comment]
@ktarbet We had the same issue with HydrometNotifications a couple weeks ago: https://github.com/BoiseState/CS471-F17-KillMinusNine/issues/95 

Summary: the solution was to install the System.Data.SQLite.Core NuGet package for the application, so that a third-party DLL wasn't needed.

**Comment by ktarbet** [comment]
Perhaps we can make a command line build at a higher level instead of within Visual Studio.

**Comment by sammcmahon** [comment]
@ktarbet I was thinking of using something more like [this](https://peteris.rocks/blog/cross-platform-builds-on-windows-and-mono-with-msbuild/) to create different directories on different platforms if needed.

I'm not sure having another build layer on top of msbuild would be maintainable in the long run, and is probably not necessary either, if just used to build the applications and libraries alone.

**Comment by sammcmahon** [comment]
I just pulled down the new changes and the build script is causing the build to fail from inside Visual Studio:

screen shot 2018-03-03 at 12 25 03 pm

In digging around the TravisCI logs, this was also causing the build to fail there as well.

**Comment by sammcmahon** [comment]
@ktarbet Can you try to recreate the SQLite error in the Pisces UI again? I pushed up a commit that could fix it.

**Comment by sammcmahon** [comment]
After doing some research, it looks like any code referencing SQLite wouldn't have run on Linux in the existing configuration. 

The DLL bundled with the repository previously was a natively compiled shared library, but natively compiled for Windows. What's needed for the Linux tests running SQLite is to either find a native Linux version of the interop library, or to get SQLite configured to not need the native portions.

http://blog.wezeku.com/2016/10/09/using-system-data-sqlite-under-linux-and-mono/
http://sqlite.1065341.n5.nabble.com/System-Data-SQLite-Using-sqlite3-dll-instead-of-Interop-dll-what-s-the-trade-off-td91484.html

**Comment by ktarbet** [comment]
@sammcmahon  Thanks! -- I've tested the PiscesUI and it works for the simple test case.   

@blounsbury Will you please check this branch for Modsim.   I have this error (see below) for Modsim, but that might be 32/64 bit Access issues.  
image

**Comment by sammcmahon** [comment]
@ktarbet Also a heads up, a fair amount of commit squashing has happened on this branch, so for people who've been editing on it previously, a pull with a rebase should probably be proactively done.

**Comment by ktarbet** [comment]
@sammcmahon  I like the way you are creating directories for different OS .  Nice!

**Comment by sammcmahon** [comment]
Rebased proactively to bring branch fully up to date with commits on master.

**Comment by ktarbet** [comment]
Thanks very much @sammcmahon and @robertherrera  --   Having unit tests running with Linux is a great improvement.

**Pull request merged**
