### PR TITLE
no encryption on empty password

### PR DESCRIPTION
**Pull request by blounsbury-usbr**
I really don't understand this, and don't have time to understand it. The code encrypts an empty string, but can't decrypt an empty string. So, setting the code to ignore encryption on an empty password.

### CODE REVIEW

**Comment by ktarbet** [comment]
Would you consider other options?

* (best) would be not to save any passwords
* consider using Windows Credential Manager

**Comment by blounsbury-usbr** [comment]
Yeah, the IT people are requiring that we move that direction with active directory/smartcard authentication to everything. But the Hydromet server isn't connected to active directory and neither the Hydromet server or Postgres database is setup to accept smartcard credentials. 

We've configured HydrometTools to use the Windows Credential Manager before it will load, but that is not good enough from the IT perspective. They want authentication to AD.

If you have thoughts or code to get this implemented we'd love it!

**Comment by ktarbet** [comment]
+10 Seriously consider connecting your database to AD;  Then you don't need to manage users/passwords, you would likely just add users to a Hydromet Role.

+5  Have users enter a password when access is required (don't save passwords)

+1 use Windows Credential manager, or something besides your own code (StringCypher) to save passwords if you require that in the short term.

HydrometTools appears to also be using the StringCypher , so if that was replaced with using Windows Credential manager, (or user entering password) that would be an improvement to both Pisces and HydrometTools.

https://github.com/usbr/HydrometTools/blob/752032c6493adc76dfc3121cd3fcdb02e8647b86/Advanced/Database.cs#L71C7-L81C10

**Comment by blounsbury-usbr** [comment]
The +10 is going to happen, just not at this moment. 

I'll go ahead with the +5 and push it into this branch/request. We'll see how much we upset people by not saving passwords.

Maybe I'm not understanding your idea, but the Postgres database isn't setup to accept credentials, it needs a username/password until we figure out how to set it up to use credentials or pass credentials to AD. So, I'm not sure how we can use Windows Credentials right now.

**Review by tjrocha — APPROVED** [review]

**Pull request merged**
