### PR TITLE
More sdk style update - dipping into .net 7.0 

### PR DESCRIPTION
**Pull request by ktarbet**

### CODE REVIEW

**Comment by blounsbury-usbr** [comment]
@ktarbet what is thought behind having .net48 and .net7.0 builds? I thought we'd just do .net7 so the output goes to bin/Debug rather than bin/Debug/net48 or net7.0 or whatever. I remember we had an issue with multi-builds previously and I changed some projects to force it to build to bin/Debug.

**Comment by blounsbury-usbr** [comment]
@ktarbet I'm also assuming we can clear out the DotNetCore projects now?

**Comment by ktarbet** [comment]
@blounsbury-usbr ,  I'm OK going with .net 7.0.  

Two reasons I took a small step first.

* some of your users would, likely, need to install .net 7 framework/runtime on windows, and need admin rights to do so.
* this gives minimal support for linux so mono could be retired for Linux command line services. (with testing of course)

I would personally prefer to just go .net 7.0. Should we just go for it?

**Comment by blounsbury-usbr** [comment]
Ah, I see. Yeah, I checked a bare computer and .net 7 isn't installed. The other issue we have is that the hydromet servers are on RHEL 7.9, which isn't compatible with .net 7. Hmmm?

**Comment by ktarbet** [comment]
We could also try .net 6.0  if that is better first step?   6.0 may work with RHEL 7.9, but not sure about your users, windows computers.   

...and .net 8.0 is coming soon.

**Comment by blounsbury-usbr** [comment]
Yeah, I doubt hydromet will want to upgrade RHEL. So, I'd say .net 6.0 would be the way to go, that version is also available in our Reclamation Software Center so it should be easy for users to get it installed. Or maybe we can work with IRM to push the .net 6 install to HydrometTools/Pisces users.

**Comment by ktarbet** [comment]
Looks like another option is publishing a standalone file to deploy.   Perhaps try to combine that with .net 6.0?

https://learn.microsoft.com/en-us/dotnet/core/deploying/single-file/overview?tabs=cli

**Comment by blounsbury-usbr** [comment]
Hmm ... apparently it's not possible to target .net6 only. If I do that I get error messages for the .net framework projects:

image

**Comment by ktarbet** [comment]
Do you have a branch to show how to reproduce that error?  Did you remove all net48 and replace with net6.0?

**Comment by blounsbury-usbr** [comment]
Kinda have a mess going on right now. If you remove net48 for Core you'll see those messages pop-up. The intrawebs say you can't reference a .net project in a .net framework project and vice versa.

**Comment by ktarbet** [comment]
Core is the foundation project , in Pisces, to almost everything so everything breaking may make sense.

**Comment by blounsbury-usbr** [comment]
Well .... I did finally get Pisces to build, I think we're closer and I'll push a branch soon for testing. I'm assuming that if a project is a console application it can be switched over to .net6?

**Comment by ktarbet** [comment]
Most Command line apps in the Pisces.sln depend on the Libraries: Core, and TimeSeries.   So depending on how you compile the libraries  (.net6.0 or .net standard 2.0) will affect your ability to switchover.

**Pull request merged**
