### PR TITLE
Appveyor

### PR DESCRIPTION
**Pull request by ktarbet**

### CODE REVIEW

**Comment by blounsbury-usbr** [comment]
I'm not fully tracking this one. Do we now need a permanent appveyor branch for the tests to run? I'd also like to get the net4.8 out of the output path as we'd also need to edit the Inno file with each .net change. I can take care of the output path unless you wanted to.

**Comment by ktarbet** [comment]
That would be great if you can take care of removing net4.8 from the output path.   This PR gets the tests working again, close to what is in master without needed to run a command line test.

**Comment by ktarbet** [comment]
Your are right we don't need a appveyor branch, but having appveyor-branch  in appveyor.yml gets appveyor  running
i

**Comment by blounsbury-usbr** [comment]
I think I'm confusing myself. So, if the last commit works, do we delete the appveyor-branch from appveyor.yml before merging so we can delete the appveyor branch? That's an interesting sentence, hahaha...

**Comment by blounsbury-usbr** [comment]
Staring at the two appveyor builds, I think I know the answer. Yes, we can now remove the appveyor-branch from the yml as we figured out why tests weren't working on master. Going to commit that...

**Review by blounsbury-usbr — APPROVED** [review]

**Pull request merged**
