### PR TITLE
allow series calculate without automatic database save - Hydromet Tools

### PR DESCRIPTION
**Pull request by blounsbury-usbr**
* bug fix - LookupShift() always returned 0 - Hydromet Tools

### CODE REVIEW

**Comment by blounsbury-usbr** [comment]
This is quite outside of my knowledge realm. But the edit seems to work. Pisces timeseries tests pass and hydromet tools is also correctly calculating shifts and flow. But open to discussion of how this should be correctly handled.

**Comment by ktarbet** [comment]
Sounds nice to not have automatic save -- One reason for the automatic save , was when you edit stage but want to also compute flow from a rating table, so having the stage saved in the database allowed the variable resolver to find the updated stage from the database.

Hydromet tools had a feature that would use OpenDCS to re-process some raw GOES data.  There might be some slight interaction with that component to consider.

**Comment by tjrocha** [comment]
I've been wanting to explore expanding our use of OpenDCS now that it seems to have more capabilities in terms of importing data. Other instances (HDBs and some Corps aaplications) use OpenDCS for a lot of the state and federal-partner data imports. Might be good to start moving some of our custom data loaders (IDWR, OWRD, USGS, etc) in this direction.

-- Jon

________________________________
From: Karl Tarbet ***@***.***>
Sent: Friday, September 16, 2022 10:53 AM
To: usbr/Pisces ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [EXTERNAL] Re: [usbr/Pisces] allow series calculate without automatic database save - Hydromet Tools (PR #211)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



Sounds nice to not have automatic save -- One reason for the automatic save , was when you edit stage but want to also compute flow from a rating table, so having the stage saved in the database allowed the variable resolver to find the updated stage from the database.

Hydromet tools had a feature that would use OpenDCS to re-process some raw GOES data. There might be some slight interaction with that component to consider.

**Comment by blounsbury-usbr** [comment]
Yeah, did I mention I'm not a Hydromet Tools user, haha. In this scenario without automatic save, couldn't the user:
- edit stage, hit the Save button to save it to the database
- then calculate flow, hit Save again

I can see that it is definitely more clicking without automatic save, but it's also a good safety feature so you don't accidentally write something to the database that you didn't intend to. Also nice to just see what the calculation results are prior to saving to the database.

I did see the decode raw data menu, but did not look at what it does. I'd need some explainers there.

**Review by ktarbet — APPROVED** [review]
Approved.  If you want to be extra careful you could attempt to add a unit test to demonstrate the changes.

**Comment by blounsbury-usbr** [comment]
Sounds good. I can add a test for the LookupShift bug.

**Comment by blounsbury-usbr** [comment]
@ktarbet Well, I can't figure out how to get a database test for the LookupShift to work. I add a "shift" property, but when Calculate is called the property is not there. Any ideas?

```
[Test]
public void LookupShift()
{
    _svr.CreateDataBase(_fn);

    DateTime t = new DateTime(2022, 9, 1);

    var s = HydrometInfoUtility.Read("afci", "ch", t, t, 
        TimeInterval.Irregular, HydrometHost.PNLinux);
    s.Name = "afci_ch";
    s.Properties.Set("shift", "-0.42");

    var c = new CalculationSeries();
    c.TimeInterval = TimeInterval.Irregular;
    c.Name = "afci_hh";
    c.Expression = "LookupShift(afci_ch)";

    _db.AddSeries(s);
    _db.AddSeries(c);

    c.Calculate();

    Assert.AreEqual(-0.42, c[0].Value, 0.001);
}
```

**Comment by ktarbet** [comment]
@blounsbury-usbr  I think you need a variable resolver.

```csharp
 s.Parser.VariableResolver = new VariableResolver();

**Comment by blounsbury-usbr** [comment]
@ktarbet Hmm ... adding a variable resolver and variable does the same thing.

```c#
c.Parser.VariableResolver = new VariableResolver();
c.Parser.VariableResolver.Add("afci_ch", s);
c.Parser.RecursiveCalculations = true;
```

From what I see the issue is that the shift property is missing. If I open the temp pdb in Pisces the property is not there. Tried adding saveproperties call which did not help.

```c#
_db.SaveProperties(s);
```

**Comment by blounsbury-usbr** [comment]
@ktarbet Well, found a workaround by moving the AddSeries call before setting the property.

But it seems we have a series properties bug. When calling, _db.SaveProperties(s), it is saving the seriescatalog but the properties are in seriesproperties. So, nothing gets saved. Maybe this was intentional as the series properties are edited with the GUI, or maybe you were in the midst of implementing this fully?

**Pull request merged**
