### PR TITLE
RiverwareDMI

### PR DESCRIPTION
**Pull request by blounsbury**
* For Yakima with mrm_init parameter, pull hydromet from first of the month

### CODE REVIEW

**Review by ktarbet — APPROVED** [review]
@blounsbury  This looks reasonable.   Another option may be to put something the config.  I think there is some sort of text file for the dmi configuration.

**Comment by blounsbury** [comment]
@ktarbet This is a new control file parameter that I added last year when developing a RiverWare MRM model. So, it is input as !mrm_init=true in the control file. I think I got confused by the parameter options available, daysOffset and dayCount. I just wanted a single value at the models init timestep (e.g., starting storage) but didn't figure out how to make that work so I added mrm_init. Now that we realized we a value at the start of month, I don't think daysOffset or dayCount would work as we don't know how many days there are from whenever the model is run to the start of the month.

**Comment by ktarbet** [comment]
Would a new parameter like endOfMonth=true|false  make the coding easier?

**Comment by blounsbury** [comment]
Hmm. Maybe firstOfMonth? Could then use mrm_init=true|false, and then firstOfMonth to specify if data is requested from the first of the month to the init timestep or only the init timestep. Kind of like that idea.

**Comment by ktarbet** [comment]
> @ktarbet How's this? Rather than assuming Yakima needs first of month data, just use the days_offset parameter to pull 31 days prior which gives the model a first of month value.

Nice ! -- That feels better -- not having code that checks what server.

**Comment by blounsbury** [comment]
Great. It made more sense to me too after I finally thought it through. Closing and merging...

**Pull request merged**
