### PR TITLE
add ensemble to project file

### PR DESCRIPTION
**Pull request by ktarbet**
Will you please include this in the next Pisces build.   I don't have the third party tools to make an 'official' release.

,

### CODE REVIEW

**Comment by ktarbet** [comment]
I've attached a sample database for this new feature.

[pisces-ensemble-test.zip](https://github.com/usbr/Pisces/files/3952992/pisces-ensemble-test.zip)

**Comment by tjrocha** [comment]
Looks good to me. 
image

**Comment by ktarbet** [comment]
I can see we need to add a TimeInterval column

**Comment by tjrocha** [comment]
I built a new installer, installed from compiled installer, and see the error below opening the attached file. I can open the file compiling from source with VS. Are there additional entries I need to add to InnoSetup for this new feature?

image

**Comment by tjrocha** [comment]
*sigh* nevermind. I uninstalled first and reinstalled. it works now... Updating installer file in the Releases section

**Pull request merged**
